{
 "title": "Time Distribution",
 "time": { "from": "2018-09-30T22:00:00.000Z", "to": "2018-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "Method",
    "query": "select distinct(method) m from sparkify_logs order by m asc"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "select distinct(status) as s from sparkify_logs order by s asc"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "select distinct(level) l from sparkify_logs order by l asc"
   },
   {
    "name": "auth",
    "label": "Auth",
    "query": "select distinct(auth) a from sparkify_logs order by a asc"
   },
   {
    "name": "page",
    "label": "Page",
    "query": "select distinct(page) p from sparkify_logs order by p asc"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Methods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  method as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  method\norder by time"
    }
   ]
  },
  {
   "title": "Auths",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  auth as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  auth\norder by time"
    }
   ]
  },
  {
   "title": "Page",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  page as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  page\norder by time"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  status as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  status\norder by time"
    }
   ]
  },
  {
   "title": "Gender",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  gender as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  gender\norder by time"
    }
   ]
  },
  {
   "title": "Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  level as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  level\norder by time"
    }
   ]
  },
  {
   "title": "Browser",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  userAgent_browser_family as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  userAgent_browser_family\norder by time"
    }
   ]
  },
  {
   "title": "OS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(timestamp,'$interval') as time,\n  userAgent_os_family as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  time,\n  userAgent_os_family\norder by time"
    }
   ]
  }
 ]
}