{
 "title": "Value distribution",
 "time": { "from": "2018-09-30T22:00:00.000Z", "to": "2018-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "Method",
    "query": "select distinct(method) m from sparkify_logs order by m asc"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "select distinct(status) as s from sparkify_logs order by s asc"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "select distinct(level) l from sparkify_logs order by l asc"
   },
   {
    "name": "auth",
    "label": "Auth",
    "query": "select distinct(auth) a from sparkify_logs order by a asc"
   },
   {
    "name": "page",
    "label": "Page",
    "query": "select distinct(page) p from sparkify_logs order by p asc"
   }
  ]
 },
 "panels": [
  {
   "title": "Method counts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  method as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  method"
    }
   ]
  },
  {
   "title": "Auth counts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  auth as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  auth"
    }
   ]
  },
  {
   "title": "Page counts",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  page as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  page"
    }
   ]
  },
  {
   "title": "Status counts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  status::text as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  status"
    }
   ]
  },
  {
   "title": "Gender counts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  gender as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  gender"
    }
   ]
  },
  {
   "title": "Level counts",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  level as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  level"
    }
   ]
  },
  {
   "title": "Browser Family counts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  userAgent_browser_family as metric,\n  count(*) as value\nfrom \n  sparkify_logs \nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  userAgent_browser_family"
    }
   ]
  },
  {
   "title": "Browser OS Counts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  now() as time,\n  userAgent_os_family as metric,\n  count(*) as value\nfrom \n  sparkify_logs\nwhere \n  $__timeFilter(timestamp)\n  and method in ($method)\n  and status in ($status)\n  and level in ($level)\n  and auth in ($auth)\n  and page in ($page)\ngroup by\n  userAgent_os_family"
    }
   ]
  }
 ]
}