{
 "title": "Value Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Distinct Methods",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(method)\nfrom sparkify_logs "
    }
   ]
  },
  {
   "title": "Distinct User Agents",
   "type": "table",
   "gridPos": { "h": 19, "w": 11, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(useragent)\nfrom sparkify_logs "
    }
   ]
  },
  {
   "title": "OS",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(userAgent_os_family)\nfrom sparkify_logs "
    }
   ]
  },
  {
   "title": "Distinct Page",
   "type": "table",
   "gridPos": { "h": 19, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(page)\nfrom sparkify_logs "
    }
   ]
  },
  {
   "title": "Distinct Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(status)\nfrom sparkify_logs "
    }
   ]
  },
  {
   "title": "Distinct Auth",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(auth)\nfrom sparkify_logs "
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(userAgent_browser_family)\nfrom sparkify_logs "
    }
   ]
  },
  {
   "title": "Distinct Gender",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct(gender)\nfrom sparkify_logs "
    }
   ]
  }
 ]
}